# This workflow will do a clean install of node dependencies, then use serverless framework to compile and build typescript

name: Do a Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: npm i

      - name: Typescript compiler check
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
