# This workflow will do a clean install of node dependencies, then use serverless framework to compile and build typescript and deploy to AWS

name: serverless-deploy

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install dependencies
        run: npm i

      - name: Install serverless
        run: npm i -D serverless

      - name: Serverless build
        run: npm run build
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
