# This workflow will do a clean install of node dependencies, then use serverless framework to compile and build typescript and deploy to AWS

name: dev-build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install dependencies
        run: npm i

      - name: Typescript compiler check
        run: npm run lint

      - name: Run tests
        run: npm run test
